// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Shared.Kafka.SchemaRegistry
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using global::Avro;
    using global::Avro.Specific;
    public partial class DownloadedEventInfo : ISpecificRecord
    {
        public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"DownloadedEventInfo\",\"namespace\":\"Shared.Kafka.Schema" +
                "Registry\",\"fields\":[{\"name\":\"uri\",\"type\":[\"string\",\"null\"]},{\"name\":\"location\",\"" +
                "type\":[\"string\",\"null\"]}]}");
        private string _uri;
        private string _location;
        public virtual Schema Schema
        {
            get
            {
                return DownloadedEventInfo._SCHEMA;
            }
        }
        public string uri
        {
            get
            {
                return this._uri;
            }
            set
            {
                this._uri = value;
            }
        }
        public string location
        {
            get
            {
                return this._location;
            }
            set
            {
                this._location = value;
            }
        }
        public virtual object Get(int fieldPos)
        {
            switch (fieldPos)
            {
                case 0: return this.uri;
                case 1: return this.location;
                default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
            };
        }
        public virtual void Put(int fieldPos, object fieldValue)
        {
            switch (fieldPos)
            {
                case 0: this.uri = (System.String)fieldValue; break;
                case 1: this.location = (System.String)fieldValue; break;
                default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
            };
        }
    }
}
